### PR TITLE
Adding Anderson acceleration for equilibrium

### PR DESCRIPTION
**Pull request by mfkasim1**

### CODE REVIEW

**Comment by KarimAED** [comment]
Looks good! Only one question: looking at the tests for the 3.9 build, there are 2 expected failures which are caught. What are those / shouldn't we fix them at some point?

**Review by KarimAED — APPROVED** [review]
Looks good!

**Comment by mfkasim1** [comment]
> Looks good! Only one question: looking at the tests for the 3.9 build, there are 2 expected failures which are caught. What are those / shouldn't we fix them at some point?

They are:
```
def test_solve_A_methods(dtype, device, method):

    if dtype in [torch.complex128, torch.complex64]:
        if method in ["scipy_gmres", "gmres"]:
            pytest.xfail("%s does not work for complex input" % method)
```
It's a matter of implementing it in the future for complex inputs.

**Comment by mfkasim1** [comment]
Thanks for the review!

**Pull request merged**
